#ifndef BUFFER_MGR_STAT_H
#define BUFFER_MGR_STAT_H

#include "buffer_mgr.h"

// Below are debug functions
void SHOW_BUFFER_POOL_CONTENT (BUFFER_MANAGER_BUFFERPOOL *const BM);
void SHOW_PAGE_CONTENT (BUFFER_MANAGER_PAGEHANDLE *const PAGE);
char *STRINGIFY_BUFFER_POOL_CONTENT (BUFFER_MANAGER_BUFFERPOOL *const BM);
char *STRINGIFY_PAGE_CONTENT (BUFFER_MANAGER_PAGEHANDLE *const PAGE);

#endif
