#include "storage_mgr.h"
#include "buffer_mgr_stat.h"
#include "buffer_mgr.h"
#include "dberror.h"
#include "test_helper.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>


// Variable used for storing the name of the current test.
char *TEST_NAME;

// Verify if the content of a buffer pool matches the EXPECTED content.

// (provided in the format generated by sprintPoolContent)
#define ASSERTEQUALSPOOL(EXPECTED,BM,OUTPUT)                    \
do {                                    \
char *REAL;                                \
char *_exp = (char *) (EXPECTED);                                   \
REAL = STRINGIFY_BUFFER_POOL_CONTENT(BM);                    \
if (strcmp((_exp),REAL) != 0)                    \
{                                    \
printf("[%s-%s-L%i-%s] FAILED: EXPECTED <%s> but was <%s>: %s\n",TESTINFO, _exp, REAL, OUTPUT); \
free(REAL);                            \
exit(1);                            \
}                                    \
printf("[%s-%s-L%i-%s] OK: EXPECTED <%s> and was <%s>: %s\n",TESTINFO, _exp, REAL, OUTPUT); \
free(REAL);                                \
} while(0)

// test and helper methods
static void TEST_CREATING_AND_READING_DUMMY_PAGES (void);
static void CREATE_DUMMY_PAGES(BUFFER_MANAGER_BUFFERPOOL *BM, int num);
static void CHECK_DUMMY_PAGES(BUFFER_MANAGER_BUFFERPOOL *BM, int num);

static void TEST_READ_PAGE (void);

static void testClock (void);


// main method
int
main (void)
{
    INIT_STORAGE_MANAGER();
    TEST_NAME = "";
    
    TEST_CREATING_AND_READING_DUMMY_PAGES();
    TEST_READ_PAGE();
  
    testClock();
    
    return 0;
}

void
TEST_CREATING_AND_READING_DUMMY_PAGES (void)
{
  BUFFER_MANAGER_BUFFERPOOL *BM = MAKE_POOL();
  TEST_NAME = "Creating and Reading Back Dummy Pages";

  CHECK(CREATE_PAGE_FILE("testbuffer.bin"));

  CREATE_DUMMY_PAGES(BM, 22);
  CHECK_DUMMY_PAGES(BM, 20);

  CREATE_DUMMY_PAGES(BM, 10000);
  CHECK_DUMMY_PAGES(BM, 10000);

  CHECK(DESTROY_PAGE_FILE("testbuffer.bin"));

  free(BM);
  TESTDONE();
}


void
CREATE_DUMMY_PAGES(BUFFER_MANAGER_BUFFERPOOL *BM, int NUM)
{
    int i;
    BUFFER_MANAGER_PAGEHANDLE *h = MAKE_PAGE_HANDLE();
    
    CHECK(INIT_BUFFER_POOL(BM, "testbuffer.bin", 3, RS_FIFO, NULL));
    
    for (i = 0; i < NUM; i++)
    {
        CHECK(PIN_PAGE(BM, h, i));
        sprintf(h->data, "%s-%i", "Page", h->PAGE_NUM);
        CHECK(MARK_DIRTY(BM, h));
        CHECK(UNPIN_PAGE(BM,h));
    }
    
    CHECK(SHUTDOWN_BUFFER_POOL(BM));
    
    free(h);
}
void 
CHECK_DUMMY_PAGES(BUFFER_MANAGER_BUFFERPOOL *BM, int NUM)
{
  int i;
  BUFFER_MANAGER_PAGEHANDLE *h = MAKE_PAGE_HANDLE();
  char *EXPECTED = malloc(sizeof(char) * 512);

  CHECK(INIT_BUFFER_POOL(BM, "testbuffer.bin", 3, RS_FIFO, NULL));

  for (i = 0; i < NUM; i++)
    {
      CHECK(PIN_PAGE(BM, h, i));

      sprintf(EXPECTED, "%s-%i", "Page", h->PAGE_NUM);
      ASSERTEQUALSSTRING(EXPECTED, h->data, "reading back dummy page content");

      CHECK(UNPIN_PAGE(BM,h));
    }

  CHECK(SHUTDOWN_BUFFER_POOL(BM));

  free(EXPECTED);
  free(h);
}
void
TEST_READ_PAGE ()
{
  BUFFER_MANAGER_BUFFERPOOL *BM = MAKE_POOL();
  BUFFER_MANAGER_PAGEHANDLE *h = MAKE_PAGE_HANDLE();
  TEST_NAME = "Reading a page";

  CHECK(CREATE_PAGE_FILE("testbuffer.bin"));
  CHECK(INIT_BUFFER_POOL(BM, "testbuffer.bin", 3, RS_FIFO, NULL));
  
  CHECK(PIN_PAGE(BM, h, 0));
  CHECK(PIN_PAGE(BM, h, 0));

  CHECK(MARK_DIRTY(BM, h));

  CHECK(UNPIN_PAGE(BM,h));
  CHECK(UNPIN_PAGE(BM,h));

  CHECK(FORCE_PAGE(BM, h));

  CHECK(SHUTDOWN_BUFFER_POOL(BM));
  CHECK(DESTROY_PAGE_FILE("testbuffer.bin"));

  free(BM);
  free(h);

  TESTDONE();
}



// Evaluate the clock page replacement strategy
void
testClock(void)
{
    // EXPECTED results
    const char *poolContents[]= {
        
    "[3x0],[-1 0],[-1 0],[-1 0]",
    "[3x0],[2 0],[-1 0],[-1 0]",
    "[3x0],[2 0],[0 0],[-1 0]",
    "[3x0],[2 0],[0 0],[8 0]",
    "[4 0],[2 0],[0 0],[8 0]",
    "[4 0],[2 0],[0 0],[8 0]",
    "[4 0],[2 0],[5 0],[8 0]",
    "[4 0],[2 0],[5 0],[0 0]",
    "[9 0],[2 0],[5 0],[0 0]",
    "[9 0],[8 0],[5 0],[0 0]",
    "[9 0],[8 0],[3x0],[0 0]",
    "[9 0],[8 0],[3x0],[2 0]"
    };
    const int orderRequests[]= {3,2,0,8,4,2,5,0,9,8,3,2};
        
    int i;
    int snapshot = 0;
    BUFFER_MANAGER_BUFFERPOOL *BM = MAKE_POOL();
    BUFFER_MANAGER_PAGEHANDLE *h = MAKE_PAGE_HANDLE();
    TEST_NAME = "Testing CLOCK page replacement";

    CHECK(CREATE_PAGE_FILE("testbuffer.bin"));
    CREATE_DUMMY_PAGES(BM, 100);
    CHECK(INIT_BUFFER_POOL(BM, "testbuffer.bin", 4, RS_CLOCK, NULL));
    
    for (i=0;i<4;i++)
    {
    PIN_PAGE(BM,h,orderRequests[i]);
	if(orderRequests[i] == 3)
		MARK_DIRTY(BM,h);
        UNPIN_PAGE(BM,h);
        ASSERTEQUALSPOOL(poolContents[snapshot++], BM, "check pool content using pages");
    }
    
    FORCE_FLUSH_POOL(BM);
    // check number of write IOs
    ASSERTEQUALSINT(1, GET_NUM_WRITE_IO(BM), "check number of write I/Os");
    ASSERTEQUALSINT(4, GET_NUM_READ_IO(BM), "check number of read I/Os");
    
    CHECK(SHUTDOWN_BUFFER_POOL(BM));
    CHECK(DESTROY_PAGE_FILE("testbuffer.bin"));
    
    free(BM);
    free(h);
    TESTDONE();
}


